### PR TITLE
Feature/30 favicon mmm

### PR DESCRIPTION
**Pull request by TE4-Daniel-Kull**
Veri useful

### CODE REVIEW

**Comment by TE4-Daniel-Kull** [comment]
asshol

**Comment by TE4-Daniel-Kull** [comment]
no
you bad

**Comment by TE4-jacob-klaren** [comment]
yup

**Comment by TE4-Daniel-Kull** [comment]
stahp

**Comment by TE4-jacob-klaren** [comment]
book### 

> _**ihusr**_

**Pull request merged**
